version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
      target: runner
    image: habit-app:latest
    ports:
      - "12001:3000"
    env_file:
      - server/.env
    restart: unless-stopped